name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Debug Artifacts
        run: echo "Checking the contents of the dist directory"

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: "github-pages"
