name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      # - name: Debug Artifacts
      #   run: echo "Checking the contents of the dist directory"

      # - name: Upload Artifacts
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     name: "github-pages"
      #     path: dist

      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     artifact_name: "github-pages"


      - name: Install Playwright Browsers
        run: |
          yarn exec playwright install chromium

      - name: Run Playwright tests against the build
        run: |
         yarn test
  
      - name: Generate Test Report
        run: npx ts-node tests/generate-test-report.ts

      - name: Upload artifacts if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/**/*.webm
            test-results/**/*.png
            test-results/**/*.zip

      - name: Configure Git
        run: |
          git config --global user.email "gauravjobs25@gmail.com"
          git config --global user.name "gauravthorath"

      - name: Deploy to GitHub Pages
        run: yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # This token is provided automatically by GitHub Actions
