name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Install Playwright Browsers
        run: |
          pnpm exec playwright install chromium

      - name: Run Playwright tests against the build
        run: |
          pnpm test

      - name: Publish CTRF Detailed Test Summary Results
        run: npx github-actions-ctrf ctrf/ctrf-report.json
        if: always()

      - name: Upload artifacts if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/**/*.webm
            test-results/**/*.png
            test-results/**/*.zip

      - name: Configure Git
        run: |
          git config --global user.email "gauravjobs25@gmail.com"
          git config --global user.name "gauravthorath"

      - name: Deploy to GitHub Pages
        run: pnpm deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # This token is provided automatically by GitHub Actions
