name: ORT 

on:
  schedule:
    # - cron: '0 0 * * *'
    - cron: '12 0 * * *'
    # - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "ort"
  cancel-in-progress: true

jobs:
  ort:
    name: ORT Checkpoint
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1